insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (   'CSE105'    ,   'Structured Programming Language',4	,	0	,	20	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE107'	,	'Object Oriented Programming'	,	4	,	0	,	20	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE109'	,	'Electrical Circuits '	,	4	,	0	,	20	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE205'	,	'Discrete Mathematics '	,	3	,	4	,	60	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE207'	,	'Data Structures '	,	4	,	4	,	60	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE225'	,	'Numerical Methods'	,	4	,	4	,	60	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE245'	,	'Algorithms '	,	4	,	4	,	60	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE248'	,	'Signals and Systems '	,	4	,	4	,	60	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE251'	,	'Electronic Circuits '	,	4	,	4	,	60	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE301'	,	'Database Systems '	,	4	,	25	,	79	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE325'	,	'Operating Systems '	,	4	,	25	,	79	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE345'	,	'Digital Logic Design '	,	4	,	25	,	79	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE350'	,	'Data Communications '	,	3	,	25	,	79	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE360'	,	'Computer Architecture '	,	3	,	25	,	79	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE365'	,	'Artificial Intelligence'	,	4	,	25	,	79	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE375'	,	'Compiler Design '	,	3	,	25	,	79	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE405'	,	'Computer Networks '	,	4	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE411'	,	'Software Engineering and Information System Design '	,	4	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE442'	,	'Microprocessors and Microcontrollers'	,	4	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE498'	,	'Social and Professional Issues in Computing'	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE413 '	,	'Automata Theory and Theory of Computations '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE460 '	,	'Programming Language principles '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE478'	,	'Stochastic Processes '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE482'	,	'Parallel Computation '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE483'	,	'Graph Theory '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE484'	,	'Computational Geometry '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE485'	,	'Advanced Algorithm '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE486'	,	'Bioinformatics Algorithms'	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE409'	,	'Systems Programming '	,	4	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE420'	,	'Computer Graphics '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE422'	,	'Simulation and Modeling '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE433'	,	'Wireless Programming '	,	4	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE434'	,	'Enterprise Application Design and Development '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE435'	,	'Software Quality Assurance '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE441'	,	'Component Based Design and Development '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE452'	,	'Distributed Systems and Algorithms '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE464'	,	'Advanced Database System '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE460'	,	'Web Database Programming'	,	4	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE451'	,	'Advanced Data Communication '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE453'	,	'Wireless Networks '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE454'	,	'Multimedia Communications '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE455'	,	'Optical Networks '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE456'	,	'Wide Area Networks '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE457'	,	'Cellular Networks'	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE437'	,	'Advanced Computer Architecture '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE439'	,	'Advanced Digital Logic Design '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE444'	,	'Fault Tolerant System '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE460'	,	'VLSI Design '	,	4	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE492'	,	'Robotics '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE493'	,	'Embedded Systems'	,	4	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE470'	,	'Expert System '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE474'	,	'Pattern Recognition '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE475'	,	'Machine Learning '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE476'	,	'Soft Computing '	,	4	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE477'	,	'Data Mining'	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE432'	,	'Digital Signal Processing '	,	4	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE436'	,	'Multimedia Design and Development '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE438'	,	'Digital Image Processing '	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE440'	,	'Data Compression'	,	3	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'N/A'	,	'N/A'	,	0	,	0	,	0	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE497'	,	'Thesis/Project'	,	4	,	60	,	93	,	'CSE'	);
insert into courses(course_code, course_title, course_credit, course_min_credit, course_max_credit, course_dept) values (	'CSE480'	,	'Web Programmingt'	,	4	,	60	,	93	,	'CSE'	);